require 'dotenv'
Dotenv.load

default_platform(:ios)

platform :ios do
  desc "deploy ios app"
  lane :deploy do

    project_name = "Runner.xcodeproj"
    workspace_name = "Runner.xcworkspace"
    scheme_name = "Runner"
    output_directory = "build/ios/iphoneos"
    ipa_path = "#{output_directory}/#{scheme_name}.ipa"
    release_notes_file = ENV['PWD'] + "/fastlane/release_note.txt"

    # prepare cocoapods
    sh "(cd ../ && gem install cocoapods && pod install)"

    # flutter build
    Dir.chdir "../.." do
      sh("flutter", "clean")
      sh("flutter", "pub", "get")
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end

    # xcode archive
    build_app(
      workspace: workspace_name,
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: {
          ENV['APP_IDENTIFIER'] => ENV['PROVISIONING']
        },
        signingStyle: "manual"
      },
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "#{scheme_name}.ipa",
      output_directory: "#{output_directory}"
    )

    # deploy
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      service_credentials_file: ENV['GOOGLE_APPLICATION_CREDENTIALS'],
      ipa_path: ipa_path,
      groups: ENV['GROUPS'],
      release_notes_file: release_notes_file,
    )
  end
end
